on:
  push:
    branches:
      - master



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "login to dockehub"
        run: docker login --username nadaadel19 --password dckr_pat_TBDIxcSVg3K4MI--pyDDPH-rJeg
     
